defaults:
  - base_wrap_handler@mriqc_anat_T1w

mriqc_anat_T1w:
  # TODO: would this pattern really work in general?
  pattern:
    - "*-mriqc/**/anat/*_T1w.json"
  label: mriqc_anat_T1w
  loader:
    name: load_json_dict
  example: mriqc_anat_T1w.json
  # Override dtypes to pickle for fields containing nested data.
  # TODO: what would happen if we didn't do this? I guess the fields would be
  # typed as struct with a rigid schema inferred from the example. What would
  # happen with schema violations?
  fields:
    bids_meta: pickle
    provenance: pickle
