defaults:
  - _self_

# Output config
output:
  # Top-level database directory. Table partitions are organized as:
  #   {db_dir} / {table_name} / {run_id} / {task_id} / {part}.parquet
  db_dir: ???
  # Logging directory, shared across runs. Individual run logs go in a subdirectory
  # according to run_id.
  log_dir: ???
  # Unique ID for the current run
  run_id: ???

# Parallel worker config
workers:
  # Session directories are assigned to task workers to process based on their ID.
  # TODO: It might be worth inferring these from slurm. But then that might be a bit too
  # much hiding stuff from the user.
  task_id: 0
  # Total number of task workers.
  num_tasks: 1
  # Time in seconds one process will wait at a synchronization point.
  sync_timeout: 20.0

paths:
  # List of session directories to process. Can be one of the following:
  #   - A list of directory paths and/or glob patterns.
  #   - A single path pointing to '*.txt' or '*.npy' file containing an
  #     array of directory paths/glob patterns.
  list: ???

  # If true, the pattern '**' will match any files and zero or more directories and
  # subdirectories.
  glob_recursive: true

  # Exclude paths that have alreadly been successfully processed.
  filter_completed: true
  # Paths that were processed previously but whose error rates exceed this threshold
  # will be re-processed. Set to null to disable.
  redo_error_rate_threshold: 0.25

  # Minimum number of paths to assign to each task.
  min_per_task: null

# Table definitions, each containing:
#   name: Name of the table
#   indexer: `Indexer` config. The `Indexer` name should be registered in the
#     `INDEXER_CATALOG` using the `register_indexer()` decorator. The remaining fields
#     are passed along to the `Indexer.from_config()` constructor.
#   handlers: A list of handler names or glob patterns. Each should correspond to one or
#     more handlers registered in the `HANDLER_CATALOG`.
tables:
  - name: anat
    indexer:
      name: bids_indexer
      columns:
        - name: subject
          key: sub
        - name: session
          key: ses
    handlers:
      - mriqc_anat_handler

  - name: func
    indexer:
      name: bids_indexer
      columns:
        - name: subject
          key: sub
        - name: session
          key: ses
        - name: task
        - name: run
          dtype: int
    handlers:
      - mriqc_func_handler

# `Crawler` options
crawler:
  max_threads: 8
  max_failures: null

# `BufferedParquetWriter` options
writer:
  partition_size: 64MiB
  coerce: false

# List of python modules to import for e.g. Handler and Indexer definitions.
include_modules: []

# Configure the processing run but don't run anything
dry_run: false

# Logging level
log_level: INFO
