# Hydra defaults list specifying how to compose the final config.
# The composition order is:
defaults:
  # A special reference to this config file
  - _self_
  # The base bids2table config defined in `bids2table.config.base`
  - base
  # Group configs for the `tables` group
  - tables:
    - mriqc_anat
    - mriqc_func

# Make sure Hydra can find the built-in configs.
# Configs located outside bids2table must include these lines.
hydra:
  searchpath:
    - pkg://bids2table.config
